# Generated by Django 4.1.2 on 2022-12-04 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='ubicacion')),
                ('telefono', models.CharField(max_length=150, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=150, verbose_name='direccion')),
                ('pagina_web', models.CharField(max_length=150, verbose_name='pagina_web')),
                ('url_img', models.ImageField(max_length=200, upload_to='imagenes/', verbose_name='url_img')),
                ('baja', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.CreateModel(
            name='Gastronomia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='ubicacion')),
                ('telefono', models.CharField(max_length=150, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=150, verbose_name='direccion')),
                ('pagina_web', models.CharField(max_length=150, verbose_name='pagina_web')),
                ('url_img', models.ImageField(max_length=200, upload_to='imagenes/', verbose_name='url_img')),
                ('baja', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Gastronomias',
            },
        ),
        migrations.CreateModel(
            name='PuntosInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='ubicacion')),
                ('telefono', models.CharField(max_length=150, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=150, verbose_name='direccion')),
                ('pagina_web', models.CharField(max_length=150, verbose_name='pagina_web')),
                ('url_img', models.ImageField(max_length=200, upload_to='imagenes/', verbose_name='url_img')),
                ('baja', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Puntos de Interes',
            },
        ),
        migrations.CreateModel(
            name='TipoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=50, verbose_name='asunto')),
            ],
        ),
        migrations.CreateModel(
            name='ZonasAlojamientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('ubicacion', models.CharField(max_length=150, verbose_name='ubicacion')),
                ('telefono', models.CharField(max_length=150, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=150, verbose_name='direccion')),
                ('pagina_web', models.CharField(max_length=150, verbose_name='pagina_web')),
                ('url_img', models.ImageField(max_length=200, upload_to='imagenes/', verbose_name='url_img')),
                ('baja', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Zonas de Alojamiento',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre_completo')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('email', models.EmailField(max_length=50, verbose_name='email')),
                ('mensaje', models.CharField(max_length=400, verbose_name='mensaje')),
                ('respondido', models.BooleanField(default=0)),
                ('asunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tornquist.tipoconsulta', verbose_name='asunto')),
            ],
            options={
                'verbose_name_plural': 'Consultas',
            },
        ),
    ]
