# Generated by Django 3.2.14 on 2022-11-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0002_auto_20221128_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividades',
            options={'verbose_name_plural': 'Actividades'},
        ),
        migrations.AlterModelOptions(
            name='consulta',
            options={'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='gastronomia',
            options={'verbose_name_plural': 'Gastronomias'},
        ),
        migrations.AlterModelOptions(
            name='puntosinteres',
            options={'verbose_name_plural': 'Puntos de Interes'},
        ),
        migrations.AlterModelOptions(
            name='zonasalojamientos',
            options={'verbose_name_plural': 'Zonas de Alojamiento'},
        ),
        migrations.AlterField(
            model_name='consulta',
            name='telefono',
            field=models.IntegerField(verbose_name='telefono'),
        ),
    ]
