# Generated by Django 4.1.2 on 2022-12-05 00:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0003_alter_gastronomia_options_remove_actividades_baja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, choices=[('', 'Seleccione una ubicacion'), ('Tornquist', 'Tornquist'), ('Sierra de la ventana', 'Sierra de la ventana')], max_length=200, null=True)),
                ('rubro', models.CharField(choices=[('', 'Seleccione un rubro'), ('Gastronomia', 'Gastronomia'), ('Excurciones', 'Excurciones'), ('Entretenimiento', 'Entretenimiento')], max_length=15)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_respuesta', models.CharField(blank=True, choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('En revision', 'En revision')], default='En revision', max_length=15, null=True)),
                ('sitio', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='solicitudes/%Y/%m/%d')),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='RespuestaSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('estado_solicitud', models.CharField(blank=True, choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('En revision', 'En revision')], max_length=15, null=True)),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tornquist.solicitud')),
            ],
        ),
    ]
