# Generated by Django 3.2.14 on 2022-12-07 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tornquist.validaciones


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0005_auto_20221206_2105'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='consulta',
        #     name='pendiente',
        # ),
        migrations.AddField(
            model_name='consulta',
            name='estado_respuesta',
            field=models.CharField(blank=True, choices=[('Contestada', 'Contestada'), ('No Contestada', 'No Contestada'), ('En proceso', 'En proceso')], default='No Contestada', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='mensaje',
            field=models.CharField(max_length=400, validators=[tornquist.validaciones.clean_mensaje], verbose_name='mensaje'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nombre',
            field=models.CharField(max_length=100, validators=[tornquist.validaciones.solo_caracteres], verbose_name='nombre_completo'),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('fecha', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tornquist.consulta')),
            ],
        ),
    ]