# Generated by Django 4.1.2 on 2022-12-05 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0005_rename_pagina_web_actividades_sitio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to="[('', 'Seleccione un rubro'), ('Gastronomia', 'Gastronomia'), ('Actividades', 'Actividades'), ('Puntos de interes', 'Puntos de interes'), ('Alojamiento', 'Alojamiento')]/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='rubro',
            field=models.CharField(choices=[('', 'Seleccione un rubro'), ('Gastronomia', 'Gastronomia'), ('Actividades', 'Actividades'), ('Puntos de interes', 'Puntos de interes'), ('Alojamiento', 'Alojamiento')], max_length=20),
        ),
    ]
