# Generated by Django 3.2.14 on 2022-12-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0006_auto_20221207_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='url_img',
            new_name='imagen',
        ),
    ]
