# Generated by Django 4.1.2 on 2022-12-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0006_alter_solicitud_imagen_alter_solicitud_rubro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='solicitudes/%Y/%m/%d'),
        ),
    ]
