# Generated by Django 3.2.14 on 2022-12-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0007_rename_url_img_solicitud_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='direccion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado_respuesta',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazada', 'Rechazada'), ('En revision', 'En revision')], default='En revision', max_length=15),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='sitio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='ubicacion',
            field=models.CharField(choices=[('', 'Seleccione una ubicacion'), ('Tornquist', 'Tornquist'), ('Sierra de la ventana', 'Sierra de la ventana')], max_length=200),
        ),
    ]