# Generated by Django 4.1.2 on 2022-12-05 01:27

from django.db import migrations, models
import tornquist.models


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0007_alter_solicitud_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=tornquist.models.carpetas_de_guardado),
        ),
    ]
