# Generated by Django 3.2.14 on 2022-12-07 15:29

from django.db import migrations, models
import tornquist.models
import tornquist.validaciones


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0008_auto_20221207_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='imagen',
            field=models.ImageField(blank=True, upload_to=tornquist.models.carpetas_de_guardado, validators=[tornquist.validaciones.valid_extension]),
        ),
    ]
