# Generated by Django 3.2.14 on 2022-12-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tornquist', '0009_alter_solicitud_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='email_usuario',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]